var nouns = [
  {id: 1, word: 'relay'},
  {id: 2, word: 'inversion'},
  {id: 3, word: 'interference', singular_only: true},
  {id: 4, word: 'discriminator'},
  {id: 5, word: 'signal'},
  {id: 6, word: 'capacitor'},
  {id: 7, word: 'configuration'},
  {id: 8, word: 'effect'},
  {id: 9, word: 'disturbance'},
  {id: 10, word: 'field'},
  {id: 11, word: 'phenomenon', singular_only: true},
  {id: 12, word: 'array'},
  {id: 13, word: 'emission'},
  {id: 14, word: 'domain'},
  {id: 15, word: 'subspace', singular_only: true},
  {id: 16, word: 'coupling', singular_only: true},
  {id: 17, word: 'dilithium', singular_only: true},
  {id: 18, word: 'stream'},
  {id: 19, word: 'variance'},
  {id: 20, word: 'distortion'},
  {id: 21, word: 'controller'},
  {id: 22, word: 'actuator'},
  {id: 23, word: 'continuum', singular_only: true},
  {id: 24, word: 'bank'},
  {id: 25, word: 'harmonic'},
  {id: 26, word: 'mutation'},
  {id: 27, word: 'invariance', singular_only: true},
  {id: 28, word: 'seal'},
  {id: 29, word: 'container'},
  {id: 30, word: 'generator'},
  {id: 31, word: 'filter'},
  {id: 32, word: 'manifold'},
  {id: 33, word: 'safeties', singular_only: true},
  {id: 34, word: 'buffer'},
  {id: 35, word: 'accelerator', singular_only: true},
  {id: 36, word: 'booster'},
  {id: 37, word: 'transponder'},
  {id: 38, word: 'probe'},
  {id: 39, word: 'nanoprobe'},
  {id: 40, word: 'stabilizer'},
  {id: 41, word: 'phaser'},
  {id: 42, word: 'nacelle'},
  {id: 43, word: 'field'},
  {id: 44, word: 'quantum', singular_only: true},
  {id: 46, word: 'particle'},
  {id: 47, word: 'system'},
  {id: 48, word: 'frequency'},
  {id: 49, word: 'wavefront'},
  {id: 50, word: 'plasma', singular_only: true},
  {id: 51, word: 'interface'},
  {id: 52, word: 'data', singular_only: true},
  {id: 53, word: 'access', singular_only: true},
  {id: 54, word: 'charge'},
  {id: 55, word: 'diagnostic'},
  {id: 56, word: 'mass'},
  {id: 57, word: 'nanite'},
  {id: 58, word: 'radiation', singular_only: true},
  {id: 59, word: 'rift'},
  {id: 60, word: 'biofilter'},
  {id: 61, word: 'replicator'},
  {id: 62, word: 'LCARS', singular_only: true},
  {id: 63, word: 'injector'},
  {id: 64, word: 'transporter'},
  {id: 65, word: 'tricorder'},
  {id: 66, word: 'synthehol', singular_only: true},
  {id: 67, word: 'turbolift'},
  {id: 68, word: 'engineering', singular_only: true, is_place: true},
  {id: 69, word: 'Holodeck', singular_only: true, is_place: true},
  {id: 70, word: 'astrocartography', singular_only: true, is_place: true},
  {id: 71, word: 'anomaly'}
];

exports.seed = function(knex, Promise) {
  var seedPromises = [];

  for (var index in nouns) {
      seedPromises.push(knex('nouns').insert(nouns[index]));
  }
    // Delete all, then run the updates
    return knex('nouns').del().then(function() {
        return Promise.all(seedPromises);
    });
};
